version: "3.8"

services:
  django-app:
    build:
      context: .
      dockerfile: Dockerfile.django
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ALLOWED_HOSTS=*  # Важно для тестирования

  dash-app:
    build:
      context: .
      dockerfile: Dockerfile.dash
    ports:
      - "8050:8050"
    environment:
      - API_URL=http://django-app:8000/api/mytable/
    depends_on:
      - django-app

  locust:
    build:
      context: .
      dockerfile: Dockerfile.locust
    ports:
      - "8089:8089"
    depends_on:
      - django-app
    volumes:
      - ./locustfile.py:/locustfile.py  # Для быстрого редактирования без пересборки