version: "3.8"

services:
  django-app:
    build:
      context: .
      dockerfile: Dockerfile.django
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  dash-app:
    build:
      context: .
      dockerfile: Dockerfile.dash
    ports:
      - "8050:8050"
    environment:
      - API_URL=http://django-app:8000/api/mytable/
    depends_on:
      - django-app

  locust:
    build:
      context: .
      dockerfile: Dockerfile.locust
    ports:
      - "8089:8089"
    depends_on:
      - django-app
    command:
      - locust
      - -f
      - /locustfile.py
      - --host=https://shiny-tribble-7vpx7w6qv4942gvg-8000.app.github.dev
